- name: Expense frontend setup
  hosts: all
  tasks:
    - name: Installing nginx
      ansible.builtin.dnf:
        name: nginx
        state: present
    - name: copying expense config file
      ansible.builtin.copy:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf
    - name: clean ols nginx dir
      ansible.builtin.file:
        path: /usr/share/nginx/html/
        state: absent
    - name: create nginx dir
      ansible.builtin.file:
        path: /usr/share/nginx/html/
        state: directory
    - name: download and extract frontend app
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes
    - name: starting nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: yes






