- name: Installing nginx
  ansible.builtin.dnf:
    name: nginx
    state: present
- name: copying expense config file
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Import Common Role - App Pre-requisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app-prereq
  vars:
    app_dir: /usr/share/nginx/html
    component: frontend

- name: starting nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: Import ELK role - Filebeat
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat

- name: Import Prometheus - Node Exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node-exporter

- name: Import Grafana - Dashboard Creation
  ansible.builtin.import_role:
    name: grafana

- name: Generate Alert from YML file
  ansible.builtin.template:
    src: alert-rules.yml
    dest: /tmp/alert-rules.yml

- name: Upload alert file to S3
  community.aws.s3_sync:
    bucket: g76-prometheus-alert-rules
    file_root: /tmp/alert-rules.yml
