- name: Copy elastic Yum Repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install File beat
  ansible.builtin.dnf:
    name: filebeat
    state: installed


