groups:
  - name: node_exporter
    rules:
      - alert: Instance down
        expr: up < 1
        for: 1m
        labels:
          severity: Critical
        annotations:
          summary: Instance down alert
